
const constants = {
  SORT_COLORS : "SORT_COLORS",
  ADD_COLOR : "ADD_COLOR",
  RATE_COLOR : "RATE_COLOR",
  REMOVE_COLOR: "REMOVE_COLOR",
  TOGGLE_SORTER: "TOGGLE_SORTER",

  TICK_COUNTDOWN: "TICK_COUNTDOWN",
  DRAFTED_TEAM: "DRAFTED_TEAM",

  ADD_MANAGER: "ADD_MANAGER",
  RESET_DRAFT: "RESET_DRAFT",
  TOGGLE_DRAFT_DISPLAY: "TOGGLE_DRAFT_DISPLAY",
  TOGGLE_SUB_TAB_NUM : "TOGGLE_SUB_TAB_NUM",
  ADD_TEAM_TO_QUEUE : "ADD_TEAM_TO_QUEUE",
  REMOVE_TEAM_FROM_QUEUE : "REMOVE_TEAM_FROM_QUEUE"

}

export default constants
