
const constants = {
  SORT_COLORS : "SORT_COLORS",
  ADD_COLOR : "ADD_COLOR",
  RATE_COLOR : "RATE_COLOR",
  REMOVE_COLOR: "REMOVE_COLOR",
  TOGGLE_SORTER: "TOGGLE_SORTER",

  TICK_COUNTDOWN: "TICK_COUNTDOWN",
  DRAFTED_TEAM: "DRAFTED_TEAM",

  ADD_MANAGER: "ADD_MANAGER"

}

export default constants
